### ISSUE TITLE
[8.0] UPS Integration - How Much Funding Needed For Completion?

### ISSUE THREAD

**Issue by lukebranch** [JayVora-SerpentCS/OdooUSA#3]
@JayVora-SerpentCS ,

I hope you're well. I'd like to know if the UPS integration is working in Odoo 8.0 and if not whether any injection of funding might help with the completion of development.

I'm interested in getting UPS setup for one of our retail companies and I remembered you had this project going.

I can't contribute a huge amount of funding, but could perhaps organise a couple of hundred euros on my end if this will help with development of the module.

If funding will help would you mind putting together a list of features that the module will achieve (eg. printing shipping labels from backend, and organising shipments from backend of Odoo) so that I can try to get a budget organised to help partially fund the development?

I'd be happy to also spread the word on the community mailing lists and try to get more people interested in funding as well if this will help.

If you're open to funding to get the project completed please also let me know what license you plan to release it under (I assume it will stay open-source and probably will be submitted to OCA eventually, although correct me if i'm wrong).

**Comment by JayVora-SerpentCS** [comment]
UPS is already integrated! Sorry, didn't notice the email.

**Comment by lukebranch** [comment]
@JayVora-SerpentCS ,

No problem, I understand you're super busy. I'm trying to integrate something for a retail website with UPS shipping methods. I had some trouble getting things to work properly when I checked around 4-5 months ago, but I will install again on a dev database and try to get it working, as you say it's already working.

**Comment by JayVora-SerpentCS** [comment]
Bro, you can let me if anything is missing, we can collaborate surely.

**Comment by lukebranch** [comment]
thanks mate, much appreciated. 

I'll get back to you once i've tested out all the features in sandbox mode. I'll shoot you over an email to discuss.
